name: Release

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: micksatana/steamcmd-ubuntu
      - name: Docker meta (th)
        id: meta-th
        uses: docker/metadata-action@v5
        with:
          images: micksatana/steamcmd-ubuntu
          tags: |
            suffix=th
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push (th)
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            ENABLE_LOCALES=en_US.UTF-8 th_TH.UTF-8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-th.outputs.tags }}
          labels: ${{ steps.meta-th.outputs.labels }}
